version: "3.2"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/arena_camera_ros2
    # lucid devices container can see
    command:
      ["/ArenaSDK_Linux_x64/precompiledExamples/./IpConfigUtility", "/list"]
